# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db3baa201f5781bc9c6ea966e7cc3fb98b89c3a9ca7ab51e7174ce8b3f9ec54e49da1ab02f804fd83cdd34a95f2151d7d6502c9a44f59e564ac94ac1a35b0b5e

test:
  secret_key_base: dc2f5e72497d427384ed02c15924736e77dabed3fa6a65fa8262d4a974dea6466de1fc6f4630bbdad74d7a962efa88f05db5ba3aae967413c813ff272f97acdb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
